# "build" 스테이지
FROM node:16.18-alpine AS build 
WORKDIR /app
COPY . .

RUN npm i && npm run build

FROM node:16.18-alpine
WORKDIR /root/
# "build" 스테이지의 결과물을 사용
COPY --from=build /app/dist ./dist
COPY --from=build /app/package.json ./
# 앱 실행에 붎필요한 devDependencies는 설치하지 않는다.
RUN npm i --production

CMD npm run start:prod