FROM node:16.18-alpine AS build
WORKDIR /app
COPY . .

RUN npm i 
RUN npm run build

FROM node:16.18-alpine
WORKDIR /root/
COPY --from=build /app/dist ./dist
COPY --from=build /app/package.json ./
RUN npm i --production

CMD npm run start:prod