version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    # 오류가 있을 시 재시작
    restart: on-failure
    volumes:
    - jenkins_home:/var/jenkins_home
    ports:
    - 8080:8080
    - 50000:50000
volumes:
  jenkins_home: {}
